#page title
page_title                                :                                           # Automatically populates with app name if not set and if iOS app ID is set. Otherwise enter manually.

# App Info
ios_app_id                                : 6749691074                                # Required. Enter iOS app ID to automatically populate name, price and icons (e.g. 718043190).
ios_app_country                           : fi                                        # Required outside USA. Enter 2 letter country code as in https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2

appstore_link                             :                                           # Automatically populates if not set and if iOS app ID is set. Otherwise enter manually.
playstore_link                            :                                           # Enter Google Play Store URL.
# presskit_download_link                    : https://emilbaehr.com                                          # Enter a link to downloadable file or (e.g. public Dropbox link to a .zip file). 
                                                                                      # Or upload your press kit file to assets and set path accordingly (e.g. "assets/your_press_kit.zip").

app_icon                                  : # assets/appicon.png                      # Automatically populates if not set and if iOS app ID is set.  Otherwise enter path to icon file manually.
app_name                                  :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_price                                 :                                           # Automatically populates if not set and if iOS app ID is set.  Otherwise enter manually.
app_description                           :  Mura is the easiest way to start building your legacy — guided journaling one daily prompt at a time.

enable_smart_app_banner                   : true                                      # Set to true to show a smart app banner at top of page on mobile devices.



# Information About Yourself
# your_name                                 : Emil Baehr                                
# your_link                                 : https://emilbaehr.com                     
# your_city                                 : Copenhagen                                
email_address                             : support@mura-journal.online
linkedin_username                         :                                           
linkedin_company                          :                                           
facebook_username                         :                                           
instagram_username                        : mura.journal
twitter_username                          : 
github_username                           : 
youtube_username                          :
mastodon_link                             : 



# Feature List                            Edit, add or remove features to be presented.
features                                  :

  - title                                 : Build Your Legacy
    description                           : Mura is the easiest way to start building your legacy — one daily prompt at a time. Capture your thoughts, reflections, and ideas in a safe, private space.
    fontawesome_icon_name                 : feather-alt

  - title                                 : Daily Prompts
    description                           : Get thoughtful, inspiring prompts each day to spark your writing and help you reflect with ease.
    fontawesome_icon_name                 : calendar-day

  - title                                 : Minimalist Design
    description                           : A clean, distraction-free journaling experience that keeps the focus on your words, not the interface.
    fontawesome_icon_name                 : leaf

  - title                                 : Private by Default
    description                           : Your entries are stored only on your device. They are yours, and only yours.
    fontawesome_icon_name                 : lock

  - title                                 : Export & Keep Forever
    description                           : Export your journal whenever you like to preserve your legacy beyond the app.
    fontawesome_icon_name                 : file-export

  - title                                 : Gentle Reminders
    description                           : Stay consistent with optional reminders that nudge you to write, without overwhelming you.
    fontawesome_icon_name                 : bell




# Theme Settings
topbar_color                              : "#000000"
topbar_transparency                       : 0.1
topbar_title_color                        : "#ffffff"

cover_image                               : assets/headerimage.png                    # Replace with alternative image path or image URL.
cover_overlay_color                       : "#363b3d"
cover_overlay_transparency                : 0.8                                  # Set to: blue, black, yellow, coral or white.

body_background_color                     : "#ffffff"

link_color                                : "#3E5622"

app_title_color                           : "#ffffff"
app_price_color                           : "#ffffff"
app_description_color                     : "#ffffff"

feature_title_color                       : "#000000"
feature_text_color                        : "#666666"

feature_icons_foreground_color            : "#3E5622"
feature_icons_background_color            : "#70925520"

social_icons_foreground_color             : "#70925560"
social_icons_background_color             : "#70925520"

footer_text_color                         : "#666666"













####################################################
### Jekyll Configuration. No need to touch this. ###
####################################################

# Set the Sass partials directory, as we're using @imports
sass:
  style: :compressed # You might prefer to minify using :compressed

# Exclude these files from your production _site
exclude:
  - LICENSE
  - README.md
  - CNAME

collections:
  pages:
    output: true
    permalink: /:path/

# Markdown rendering
markdown: kramdown
